
language: node_js

notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - 6
  - 7

script:
  - gulp styles:travis
  - gulp scripts:travis
  - gulp build
  - gulp build --prod
