
language: node_js

notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - 6
  - 7
  - 8

before_install:
  - rm ./package-lock.json

script:
  - gulp styles:travis
  - gulp scripts:travis
  - gulp build
  - gulp build --prod
