
language: node_js

notifications:
  email:
    on_success: never
    on_failure: never

node_js:
  - 6
  - 7
  - 8

before_install:
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - gulp styles:travis
  - gulp scripts:travis
  - gulp build
  - gulp build --prod

after_script:
  - greenkeeper-lockfile-upload
