
language: node_js

notifications:
  email: false

node_js:
  - 8
  - 7
  - 6

before_install:
  - npm install npm@latest
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - gulp styles:travis
  - gulp scripts:travis
  - gulp build
  - gulp build --prod

after_script:
  - greenkeeper-lockfile-upload
